url: "https://alejandroblancopizarro.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/webpage" # the subpath of your site, e.g. /blog
title: "Alejandro Blanco Pizarro" # the name of your site, e.g. ACME Corp.
description: "Postdoctoral Researcher"
