menu:
- {name: 'Publications', url: '/publications'}
- {name: 'Teaching', url: '/teaching'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}
- {name: 'News', url: '/news'}

social:
- {icon: 'fab fa-github fa-3x', link: 'https://github.com/alejandroBlancoPizarro'}
- {icon: 'fab fa-linkedin fa-3x', link: 'https://www.linkedin.com/in/alejandrobp/'}
- {icon: 'ai ai-google-scholar fa-3x', link: 'https://scholar.google.es/citations?user=fDb_O4kAAAAJ&hl=es&oi=ao'}
- {icon: 'fab fa-orcid fa-3x', link: 'https://orcid.org/0000-0003-4613-2079'}
